EXTENSION   = mspgist_mobilitydb
MODULES   = mspgist_mobilitydb
DATA        = mspgist_mobilitydb--1.0.sql mspgist_mobilitydb.control

PG_CONFIG ?= pg_config
PGXS = $(shell $(PG_CONFIG) --pgxs)
include $(PGXS)
